# Generated by Django 5.1 on 2024-08-21 19:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('beef', 'Beef'), ('chic', 'Chicken'), ('dess', 'Dessert'), ('lamb', 'Lamb'), ('misc', 'Miscellaneous'), ('past', 'Pasta'), ('pork', 'Pork'), ('seaf', 'Seafood'), ('side', 'Side'), ('star', 'Starter'), ('vega', 'Vegan'), ('vege', 'Vegetarian'), ('brea', 'Breakfast'), ('goat', 'Goat')], default='beef', max_length=4)),
                ('instructions', models.TextField()),
                ('image', models.CharField()),
                ('video', models.CharField()),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None)),
                ('source', models.CharField()),
            ],
        ),
    ]
