# Generated by Django 5.1 on 2024-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category_food',
            field=models.CharField(choices=[('beef', 'Beef'), ('chic', 'Chicken'), ('lamb', 'Lamb'), ('othe', 'Other'), ('past', 'Pasta'), ('pork', 'Pork'), ('seaf', 'Seafood'), ('vega', 'Vegan'), ('vege', 'Vegetarian'), ('goat', 'Goat')], default='beef', max_length=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category_meal',
            field=models.CharField(choices=[('brea', 'Breakfast'), ('ludi', 'Lunch/Dinner'), ('dess', 'Dessert'), ('side', 'Side'), ('star', 'Starter')], default='brea', max_length=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.CharField(blank=True),
        ),
    ]
